package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Addresses generated by hbm2java
 */
public class Addresses  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private Country country;
     private Integer type;
     private String address1;
     private String address2;
     private String city;
     private String state;
     private String zip;
     private Integer status;
     private Integer cuid;
     private Integer uuid;
     private Date createdAt;
     private Date updatedAt;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);

    public Addresses() {
    }

	
    public Addresses(Users users, Country country) {
        this.users = users;
        this.country = country;
    }
    public Addresses(Users users, Country country, Integer type, String address1, String address2, String city, String state, String zip, Integer status, Integer cuid, Integer uuid, Date createdAt, Date updatedAt, Set<Purchase> purchases) {
       this.users = users;
       this.country = country;
       this.type = type;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.status = status;
       this.cuid = cuid;
       this.uuid = uuid;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.purchases = purchases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getCuid() {
        return this.cuid;
    }
    
    public void setCuid(Integer cuid) {
        this.cuid = cuid;
    }
    public Integer getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }




}


