package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer id;
     private Integer parentid;
     private String name;
     private String categoryKey;
     private String meta;
     private Integer cuid;
     private Integer uuid;
     private Date createdAt;
     private Date updatedAt;
     private Set<Products> productses = new HashSet<Products>(0);

    public Categories() {
    }

    public Categories(Integer parentid, String name, String categoryKey, String meta, Integer cuid, Integer uuid, Date createdAt, Date updatedAt, Set<Products> productses) {
       this.parentid = parentid;
       this.name = name;
       this.categoryKey = categoryKey;
       this.meta = meta;
       this.cuid = cuid;
       this.uuid = uuid;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.productses = productses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getParentid() {
        return this.parentid;
    }
    
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategoryKey() {
        return this.categoryKey;
    }
    
    public void setCategoryKey(String categoryKey) {
        this.categoryKey = categoryKey;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public Integer getCuid() {
        return this.cuid;
    }
    
    public void setCuid(Integer cuid) {
        this.cuid = cuid;
    }
    public Integer getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


