package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String code;
     private String currencyCode;
     private Set<Addresses> addresseses = new HashSet<Addresses>(0);

    public Country() {
    }

    public Country(String name, String code, String currencyCode, Set<Addresses> addresseses) {
       this.name = name;
       this.code = code;
       this.currencyCode = currencyCode;
       this.addresseses = addresseses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public Set<Addresses> getAddresseses() {
        return this.addresseses;
    }
    
    public void setAddresseses(Set<Addresses> addresseses) {
        this.addresseses = addresseses;
    }




}


