package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LoginDetails generated by hbm2java
 */
public class LoginDetails  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String meta;
     private Date loginAt;
     private Date logedoutAt;
     private Set<Users> userses = new HashSet<Users>(0);

    public LoginDetails() {
    }

	
    public LoginDetails(Users users) {
        this.users = users;
    }
    public LoginDetails(Users users, String meta, Date loginAt, Date logedoutAt, Set<Users> userses) {
       this.users = users;
       this.meta = meta;
       this.loginAt = loginAt;
       this.logedoutAt = logedoutAt;
       this.userses = userses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public Date getLoginAt() {
        return this.loginAt;
    }
    
    public void setLoginAt(Date loginAt) {
        this.loginAt = loginAt;
    }
    public Date getLogedoutAt() {
        return this.logedoutAt;
    }
    
    public void setLogedoutAt(Date logedoutAt) {
        this.logedoutAt = logedoutAt;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


