package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private OrderStatus orderStatus;
     private Integer numberOfProducts;
     private BigDecimal total;
     private String meta;
     private Integer cuid;
     private Integer uuid;
     private Date createdAt;
     private Date updatedAt;

    public Orders() {
    }

	
    public Orders(Users users, OrderStatus orderStatus) {
        this.users = users;
        this.orderStatus = orderStatus;
    }
    public Orders(Users users, OrderStatus orderStatus, Integer numberOfProducts, BigDecimal total, String meta, Integer cuid, Integer uuid, Date createdAt, Date updatedAt) {
       this.users = users;
       this.orderStatus = orderStatus;
       this.numberOfProducts = numberOfProducts;
       this.total = total;
       this.meta = meta;
       this.cuid = cuid;
       this.uuid = uuid;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public OrderStatus getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(OrderStatus orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Integer getNumberOfProducts() {
        return this.numberOfProducts;
    }
    
    public void setNumberOfProducts(Integer numberOfProducts) {
        this.numberOfProducts = numberOfProducts;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public Integer getCuid() {
        return this.cuid;
    }
    
    public void setCuid(Integer cuid) {
        this.cuid = cuid;
    }
    public Integer getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


