package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer id;
     private Categories categories;
     private String sku;
     private String barcode;
     private String name;
     private BigDecimal weight;
     private Integer qty;
     private BigDecimal productPrice;
     private BigDecimal sellingPrice;
     private BigDecimal shippingPrice;
     private String meta;
     private Integer status;
     private Integer cuid;
     private Integer uuid;
     private Date createdAt;
     private Date updatedAt;
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<Purchase> purchases = new HashSet<Purchase>(0);
     private Set<ShopBag> shopBags = new HashSet<ShopBag>(0);

    public Products() {
    }

	
    public Products(Categories categories) {
        this.categories = categories;
    }
    public Products(Categories categories, String sku, String barcode, String name, BigDecimal weight, Integer qty, BigDecimal productPrice, BigDecimal sellingPrice, BigDecimal shippingPrice, String meta, Integer status, Integer cuid, Integer uuid, Date createdAt, Date updatedAt, Set<Stock> stocks, Set<Purchase> purchases, Set<ShopBag> shopBags) {
       this.categories = categories;
       this.sku = sku;
       this.barcode = barcode;
       this.name = name;
       this.weight = weight;
       this.qty = qty;
       this.productPrice = productPrice;
       this.sellingPrice = sellingPrice;
       this.shippingPrice = shippingPrice;
       this.meta = meta;
       this.status = status;
       this.cuid = cuid;
       this.uuid = uuid;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.stocks = stocks;
       this.purchases = purchases;
       this.shopBags = shopBags;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }
    public BigDecimal getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public BigDecimal getShippingPrice() {
        return this.shippingPrice;
    }
    
    public void setShippingPrice(BigDecimal shippingPrice) {
        this.shippingPrice = shippingPrice;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getCuid() {
        return this.cuid;
    }
    
    public void setCuid(Integer cuid) {
        this.cuid = cuid;
    }
    public Integer getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }
    public Set<ShopBag> getShopBags() {
        return this.shopBags;
    }
    
    public void setShopBags(Set<ShopBag> shopBags) {
        this.shopBags = shopBags;
    }




}


