package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private Addresses addresses;
     private Products products;
     private Integer quantity;
     private String telephones;
     private String email;
     private String shippingNames;
     private String billingNames;
     private String meta;
     private Date purchasedAt;

    public Purchase() {
    }

	
    public Purchase(Users users, Addresses addresses, Products products) {
        this.users = users;
        this.addresses = addresses;
        this.products = products;
    }
    public Purchase(Users users, Addresses addresses, Products products, Integer quantity, String telephones, String email, String shippingNames, String billingNames, String meta, Date purchasedAt) {
       this.users = users;
       this.addresses = addresses;
       this.products = products;
       this.quantity = quantity;
       this.telephones = telephones;
       this.email = email;
       this.shippingNames = shippingNames;
       this.billingNames = billingNames;
       this.meta = meta;
       this.purchasedAt = purchasedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Addresses getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Addresses addresses) {
        this.addresses = addresses;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getTelephones() {
        return this.telephones;
    }
    
    public void setTelephones(String telephones) {
        this.telephones = telephones;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getShippingNames() {
        return this.shippingNames;
    }
    
    public void setShippingNames(String shippingNames) {
        this.shippingNames = shippingNames;
    }
    public String getBillingNames() {
        return this.billingNames;
    }
    
    public void setBillingNames(String billingNames) {
        this.billingNames = billingNames;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public Date getPurchasedAt() {
        return this.purchasedAt;
    }
    
    public void setPurchasedAt(Date purchasedAt) {
        this.purchasedAt = purchasedAt;
    }




}


