package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ShopBag generated by hbm2java
 */
public class ShopBag  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private Products products;
     private Integer type;
     private Integer quantity;
     private Date addedAt;
     private Integer status;
     private String meta;

    public ShopBag() {
    }

	
    public ShopBag(Users users, Products products) {
        this.users = users;
        this.products = products;
    }
    public ShopBag(Users users, Products products, Integer type, Integer quantity, Date addedAt, Integer status, String meta) {
       this.users = users;
       this.products = products;
       this.type = type;
       this.quantity = quantity;
       this.addedAt = addedAt;
       this.status = status;
       this.meta = meta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Date getAddedAt() {
        return this.addedAt;
    }
    
    public void setAddedAt(Date addedAt) {
        this.addedAt = addedAt;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }




}


