package Pojos;
// Generated Jun 15, 2019 1:47:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private Integer type;
     private String firstname;
     private String lastname;
     private String mobile;
     private String email;
     private String password;
     private Integer status;
     private String rememberToken;
     private String meta;
     private Date createdAt;
     private Date updatedAt;
     private Set<Orders> orderses = new HashSet<Orders>(0);
     private Set<LoginDetails> loginDetailses = new HashSet<LoginDetails>(0);
     private Set<Purchase> purchases = new HashSet<Purchase>(0);
     private Set<LoginDetails> loginDetailses_1 = new HashSet<LoginDetails>(0);
     private Set<Addresses> addresseses = new HashSet<Addresses>(0);
     private Set<ShopBag> shopBags = new HashSet<ShopBag>(0);

    public Users() {
    }

    public Users(Integer type, String firstname, String lastname, String mobile, String email, String password, Integer status, String rememberToken, String meta, Date createdAt, Date updatedAt, Set<Orders> orderses, Set<LoginDetails> loginDetailses, Set<Purchase> purchases, Set<LoginDetails> loginDetailses_1, Set<Addresses> addresseses, Set<ShopBag> shopBags) {
       this.type = type;
       this.firstname = firstname;
       this.lastname = lastname;
       this.mobile = mobile;
       this.email = email;
       this.password = password;
       this.status = status;
       this.rememberToken = rememberToken;
       this.meta = meta;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.orderses = orderses;
       this.loginDetailses = loginDetailses;
       this.purchases = purchases;
       this.loginDetailses_1 = loginDetailses_1;
       this.addresseses = addresseses;
       this.shopBags = shopBags;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getRememberToken() {
        return this.rememberToken;
    }
    
    public void setRememberToken(String rememberToken) {
        this.rememberToken = rememberToken;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }
    public Set<LoginDetails> getLoginDetailses() {
        return this.loginDetailses;
    }
    
    public void setLoginDetailses(Set<LoginDetails> loginDetailses) {
        this.loginDetailses = loginDetailses;
    }
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }
    public Set<LoginDetails> getLoginDetailses_1() {
        return this.loginDetailses_1;
    }
    
    public void setLoginDetailses_1(Set<LoginDetails> loginDetailses_1) {
        this.loginDetailses_1 = loginDetailses_1;
    }
    public Set<Addresses> getAddresseses() {
        return this.addresseses;
    }
    
    public void setAddresseses(Set<Addresses> addresseses) {
        this.addresseses = addresseses;
    }
    public Set<ShopBag> getShopBags() {
        return this.shopBags;
    }
    
    public void setShopBags(Set<ShopBag> shopBags) {
        this.shopBags = shopBags;
    }




}


